apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buffer-code-exercise-api
  labels:
    app: buffer-code-exercise-api
  namespace: internal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buffer-code-exercise-api
    spec:
      containers:
      - name: api
        image: bufferapp/buffer-code-exercise-api:1.1
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: buffer-code-exercise-api
  labels:
    app: buffer-code-exercise-api
  namespace: internal
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <REPLACE W/ VALID CERT ARN>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
    - port: 443
      targetPort: 8888
      protocol: TCP
      name: https
  selector:
    app: buffer-code-exercise-api
  type: LoadBalancer
